# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sunmoon.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(488, 393)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 82, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 82, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 82, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.leSunrise = QtWidgets.QLineEdit(self.centralwidget)
        self.leSunrise.setEnabled(True)
        self.leSunrise.setGeometry(QtCore.QRect(110, 40, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leSunrise.setFont(font)
        self.leSunrise.setFocusPolicy(QtCore.Qt.NoFocus)
        self.leSunrise.setReadOnly(True)
        self.leSunrise.setObjectName("leSunrise")
        self.leSunset = QtWidgets.QLineEdit(self.centralwidget)
        self.leSunset.setGeometry(QtCore.QRect(110, 70, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leSunset.setFont(font)
        self.leSunset.setFocusPolicy(QtCore.Qt.NoFocus)
        self.leSunset.setReadOnly(True)
        self.leSunset.setObjectName("leSunset")
        self.leDaylight = QtWidgets.QLineEdit(self.centralwidget)
        self.leDaylight.setGeometry(QtCore.QRect(110, 100, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leDaylight.setFont(font)
        self.leDaylight.setFocusPolicy(QtCore.Qt.NoFocus)
        self.leDaylight.setReadOnly(True)
        self.leDaylight.setObjectName("leDaylight")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 82, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.deDate = QtWidgets.QDateEdit(self.centralwidget)
        self.deDate.setGeometry(QtCore.QRect(110, 10, 131, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.deDate.setFont(font)
        self.deDate.setObjectName("deDate")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 130, 82, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.leMoonPhase = QtWidgets.QLineEdit(self.centralwidget)
        self.leMoonPhase.setGeometry(QtCore.QRect(110, 130, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leMoonPhase.setFont(font)
        self.leMoonPhase.setFocusPolicy(QtCore.Qt.NoFocus)
        self.leMoonPhase.setReadOnly(True)
        self.leMoonPhase.setObjectName("leMoonPhase")
        self.gvMoon = QtWidgets.QGraphicsView(self.centralwidget)
        self.gvMoon.setGeometry(QtCore.QRect(30, 170, 211, 171))
        self.gvMoon.setFocusPolicy(QtCore.Qt.NoFocus)
        self.gvMoon.setInteractive(False)
        self.gvMoon.setObjectName("gvMoon")
        self.pbStop = QtWidgets.QPushButton(self.centralwidget)
        self.pbStop.setGeometry(QtCore.QRect(380, 280, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbStop.setFont(font)
        self.pbStop.setObjectName("pbStop")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(310, 244, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.sbInterval = QtWidgets.QSpinBox(self.centralwidget)
        self.sbInterval.setGeometry(QtCore.QRect(360, 240, 42, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sbInterval.setFont(font)
        self.sbInterval.setMaximum(60)
        self.sbInterval.setObjectName("sbInterval")
        self.pbStart = QtWidgets.QPushButton(self.centralwidget)
        self.pbStart.setGeometry(QtCore.QRect(270, 280, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbStart.setFont(font)
        self.pbStart.setObjectName("pbStart")
        self.pbSetCurrentDate = QtWidgets.QPushButton(self.centralwidget)
        self.pbSetCurrentDate.setGeometry(QtCore.QRect(270, 10, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbSetCurrentDate.setFont(font)
        self.pbSetCurrentDate.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pbSetCurrentDate.setObjectName("pbSetCurrentDate")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 320, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(260, 40, 60, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(260, 60, 60, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(260, 80, 60, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(250, 140, 71, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(260, 100, 60, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(260, 120, 60, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.lblLatitude = QtWidgets.QLabel(self.centralwidget)
        self.lblLatitude.setGeometry(QtCore.QRect(330, 40, 100, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblLatitude.setFont(font)
        self.lblLatitude.setObjectName("lblLatitude")
        self.lblLongitude = QtWidgets.QLabel(self.centralwidget)
        self.lblLongitude.setGeometry(QtCore.QRect(330, 60, 100, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblLongitude.setFont(font)
        self.lblLongitude.setObjectName("lblLongitude")
        self.lblElevation = QtWidgets.QLabel(self.centralwidget)
        self.lblElevation.setGeometry(QtCore.QRect(330, 80, 100, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblElevation.setFont(font)
        self.lblElevation.setObjectName("lblElevation")
        self.lblLocation = QtWidgets.QLabel(self.centralwidget)
        self.lblLocation.setGeometry(QtCore.QRect(330, 100, 100, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblLocation.setFont(font)
        self.lblLocation.setObjectName("lblLocation")
        self.lblTimeZone = QtWidgets.QLabel(self.centralwidget)
        self.lblTimeZone.setGeometry(QtCore.QRect(330, 140, 100, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblTimeZone.setFont(font)
        self.lblTimeZone.setObjectName("lblTimeZone")
        self.lblRegion = QtWidgets.QLabel(self.centralwidget)
        self.lblRegion.setGeometry(QtCore.QRect(330, 120, 100, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblRegion.setFont(font)
        self.lblRegion.setObjectName("lblRegion")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 488, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.deDate, self.sbInterval)
        MainWindow.setTabOrder(self.sbInterval, self.pbStart)
        MainWindow.setTabOrder(self.pbStart, self.pbStop)
        MainWindow.setTabOrder(self.pbStop, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.gvMoon)
        MainWindow.setTabOrder(self.gvMoon, self.leSunrise)
        MainWindow.setTabOrder(self.leSunrise, self.leSunset)
        MainWindow.setTabOrder(self.leSunset, self.leDaylight)
        MainWindow.setTabOrder(self.leDaylight, self.pbSetCurrentDate)
        MainWindow.setTabOrder(self.pbSetCurrentDate, self.leMoonPhase)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Sunrise:"))
        self.label_2.setText(_translate("MainWindow", "Sunset:"))
        self.label_3.setText(_translate("MainWindow", "Daylight:"))
        self.leSunrise.setText(_translate("MainWindow", "7:27 AM PST"))
        self.leSunset.setText(_translate("MainWindow", "4:17 PM PST"))
        self.leDaylight.setText(_translate("MainWindow", "8 hours, 45 minutes"))
        self.label_4.setText(_translate("MainWindow", "Date:"))
        self.label_5.setText(_translate("MainWindow", "Moon Phase:"))
        self.leMoonPhase.setText(_translate("MainWindow", "Day 23"))
        self.pbStop.setText(_translate("MainWindow", "S&top"))
        self.label_6.setText(_translate("MainWindow", "Interval:"))
        self.pbStart.setText(_translate("MainWindow", "&Start"))
        self.pbSetCurrentDate.setText(_translate("MainWindow", "&Current Date"))
        self.pushButton.setText(_translate("MainWindow", "&Quit"))
        self.label_7.setText(_translate("MainWindow", "Latitude:"))
        self.label_8.setText(_translate("MainWindow", "Longitude:"))
        self.label_9.setText(_translate("MainWindow", "Elevation:"))
        self.label_10.setText(_translate("MainWindow", "Time Zone:"))
        self.label_11.setText(_translate("MainWindow", "Location:"))
        self.label_12.setText(_translate("MainWindow", "Region:"))
        self.lblLatitude.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\"><br/></span></p></body></html>"))
        self.lblLongitude.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\"><br/></span></p></body></html>"))
        self.lblElevation.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\"><br/></span></p></body></html>"))
        self.lblLocation.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\"><br/></span></p></body></html>"))
        self.lblTimeZone.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\"><br/></span></p></body></html>"))
        self.lblRegion.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\"><br/></span></p></body></html>"))

